version: '2'
services:
  kafka-cluster:
    image: lensesio/fast-data-dev
    environment:
      - ADV_HOST=127.0.0.1
      - SAMPLEDATA=0
      - FORWARDLOGS=0
      - RUNTESTS=0
    ports:
      - 2181:2181 #zookeeper
      - 3030:3030 #landoop ui
      - 8081-8083:8081-8083 #rest, schema registry, kafka connect
      - 9581-9585:9581-9585 #jmx
      - 9092:9092 #kafka brocker
    volumes:
      - ./kafkadata/volume:/data